services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      
    volumes:
      - ~/.ssh:/opt/shady/.ssh
      - ../.devcontainer/zshrc:/opt/shady/.zshrc
      - ~/.kube:/opt/shady/.kube
      - ..:/opt/shady/code
    command: ["tail -f /dev/null"]

